sudo: required
services:
  - docker

before_install:
  - docker build -t kartheekgopal/react-ubuntu -f Dockerfile.dev .

script:
  - docker run -e CI=true kartheekgopal/react-ubuntu npm run test -- --coverage