sudo: required
services:
  - docker

before_install:
  - docker build -t kartheekgopal/react-ubuntu -f Dockerfile.dev .

script:
  - docker run -e CI=true kartheekgopal/react-ubuntu npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'ReactUbuntu-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-265208151699'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: '$SECRET_KEY'